import React, { useState } from "react";
import styled, { css } from "styled-components";
import Link from "next/link";
import { ToggleSwitch } from "../../components/ToggleSwitch";
import Head from "next/head";

const MainLayout = (props) => {
	const [isLight, setLight] = useState(false);
	const toggleTheme = () => {
		setLight(!isLight);
	};

	const InlineWrapper = styled.div`
		display: inline-block;

		width: 48px;
		height: 24px;
	`;

	return (
		<Container light={isLight} center={props.center}>
			<Head>
				<title>{props.page}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Logo className="logo">
				<Link href="/">LOGO</Link>

				<InlineWrapper onClick={() => toggleTheme()}>
					<ToggleSwitch checked={isLight} />
				</InlineWrapper>
			</Logo>
			{props.children}
		</Container>
	);
};

export default MainLayout;

const Logo = styled.div`
	height: 80px;
	width: 100%;

	position: fixed;
	top: 0;
	left: 0;
	right: 0;

	display: flex;
	align-items: center;
	padding-left: 16px;

	background-color: #328ca61a;

	font-size: 22px;
	font-weight: bold;
	color: #f1f1f1;
`;

const Container = styled.div`
	width: 100vw;
	height: 100vh;

	padding: 16px;
	padding-top: 96px;

	background-color: #1e272e;
	color: #d2dae2;
	transition: background-color 300ms linear;

	${(props) =>
		props.light &&
		css`
			background-color: #d2dae2;
			color: #1e272e;

			& .form__label {
				color: #1e272e;
			}

			& .form__field {
				color: #1e272e;
				border-bottom: 2px solid #1e272e;
			}

			& .c-btn__signup {
				border: 2px solid #1e272e;
				background: transparent;
				color: #1e272e;
				opacity: 0.6;
				cursor: not-allowed;

				&:hover {
					opacity: 0.6;
				}
			}

			& .logo {
				& a {
					color: #1e272e;
				}
			}
		`}

	${(props) =>
		props.center &&
		css`
			display: flex;
			justify-content: center;

			padding-top: 13%;
		`}
`;
